name: "HomeArcade"
version: "2.43.11"
slug: "cabinet_bridge"
description: "The premium retro gaming frontend for Home Assistant. Manage ROMs, browse systems, and launch games from your sidebar or TV."
url: "https://github.com/GlerschNersch/HomeArcade-HA"
boot: auto
arch:
  - "aarch64"
  - "amd64"
init: false
ingress: true
ingress_port: 5000
ingress_stream: true
map:
  - "media:rw"
panel_icon: "mdi:gamepad-variant"
panel_title: "HomeArcade"
hassio_api: true
homeassistant_api: false
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
options:
  max_upload_mb: 8192
  steamgriddb_api_key: ""
schema:
  max_upload_mb: "int(16,16384)"
  steamgriddb_api_key: str?